### PR TITLE
Update BridgeAuth.php

### PR DESCRIPTION
**Pull request by TuffDev**
TextFormat::RESET should work to reset the message to its original unedited state but it might not I'm not sure.  I checked the source code and it looks like that's what it does.

### CODE REVIEW

**Comment by legoboy0215** [comment]
TextFormat::RESET resets only styles, not color :) You are right :P

**Comment by legoboy0215** [comment]
Please fix the errors. You are missing quotes.

**Comment by TuffDev** [comment]
My bad, I think I got it licked.

**Comment by DALTONTASTIC** [comment]
Links should be light blue. Also spacing around link is messed up

**Pull request closed without merging**
